### PR TITLE
v0.2.0-BETA

### PR DESCRIPTION
**Pull request by izziiyt**
#13 #32 #36
#### User dictionary available.
Not applied to many test cases so I can't assure this feature is perfect.
#### Command Line interface changed
tokenize is default sub command
#### Library interface changed
light users don't have to care configuration file
#### Add tests
 ignore_test_*.py available

### CODE REVIEW

**Comment by hiroshi-matsuda-rit** [comment]
I'd like to integrate this user dictionary available version to GiNZA and spaCy Japanese language model when all the tests are passed successfully. Thanks!

**Comment by izziiyt** [comment]
@kazuma-t I want you to check how commandline/library interface changed. This PR has too many changes to review all. You can ask me any questions. (here or email)

**Comment by hiroshi-matsuda-rit** [comment]
@izziiyt Can you separate the modules which is only used for user dictionary build, as an individual package like as 'sudachipy/dictionarybuild/' ?
I suppose that the majority of the users do not need to build the user dictionaries or system dictionaries.

**Comment by hiroshi-matsuda-rit** [comment]
@izziiyt I just found a good way to integrate sudachipy for spacy without adding a dependency for sortedcontainers.
Please do not remind above question. Sorry for that.

**Pull request merged**
