### PR TITLE
Feature/debug japanese comment

### PR DESCRIPTION
**Pull request by hiroshi-matsuda-rit**
Japanese comment is causing install errors on older versions of python. @kazuma-t @izziiyt

### CODE REVIEW

**Comment by izziiyt** [comment]
@hiroshi-matsuda Can you describe what error happens ? In the future I'd like to add Japanese text in comments on some python files such as plugins like Java Sudachi, so do we have another solution ?

**Comment by hiroshi-matsuda-rit** [comment]
This is a kind of back-porting issues.
I know you have a policy supporting only python 3.5+, hence I added some by-pass conditions to the spaCy' test codes.
But spaCy's CI test environment requires to install all the packages in reuqirements.txt, and some encoding problems occurs with python 2.7.
I found some other problems around source code encoding, like #53 .
I think we should consider these compatibility issue much deeply and take enough time to discuss and solve the problems.

**Comment by hiroshi-matsuda-rit** [comment]
Please see the recent build logs in this PR of spaCy.
https://github.com/explosion/spaCy/pull/3899
`revert SudachiPy requirement to use PyPI` uses SudachiPy from PyPI.
`remove comment` uses customized SudachiPy v0.3.2 to ensure no non-latin chars.

**Comment by izziiyt** [comment]
how about using [environment_markes](https://www.python.org/dev/peps/pep-0508/#environment-markers) in requirements.txt of spaCy ?

**Comment by izziiyt** [comment]
@hiroshi-matsuda-rit I released `v0.3.3-debug` (explicitly define encoding for `open(README.md)` ). I wrote my opinion on [slack](https://sudachi-dev.slack.com/). Please read it.

**Pull request closed without merging**
